package workflow

const COLUMN_CREATED_AT = "created_at"
const COLUMN_FROM_STEP_DEFINITION_ID = "from_step_definition_id"
const COLUMN_FROM_STEP_ID = "from_step_id"
const COLUMN_ID = "id"
const COLUMN_NAME = "name"
const COLUMN_SOFT_DELETED_AT = "soft_deleted_at"
const COLUMN_STATUS = "status"
const COLUMN_STEP_DEFINITION_ID = "step_definition_id"
const COLUMN_TO_STEP_DEFINITION_ID = "to_step_definition_id"
const COLUMN_TO_STEP_ID = "to_step_id"
const COLUMN_UPDATED_AT = "updated_at"
const COLUMN_WORKFLOW_DEFINITION_ID = "workflow_definition_id"
const COLUMN_WORKFLOW_ID = "workflow_id"

const WORKFLOW_STATUS_CANCELED = "canceled"
const WORKFLOW_STATUS_COMPLETED = "completed"
const WORKFLOW_STATUS_ERROR = "error"
const WORKFLOW_STATUS_QUEUED = "queued"
const WORKFLOW_STATUS_RUNNING = "running"
const WORKFLOW_STATUS_SCHEDULED = "scheduled"
const WORKFLOW_STATUS_STOPPED = "stopped"
const WORKFLOW_STATUS_SUCCESS = "success"

const STEP_STATUS_CANCELED = "canceled"
const STEP_STATUS_COMPLETED = "completed"
const STEP_STATUS_ERROR = "error"
const STEP_STATUS_QUEUED = "queued"
const STEP_STATUS_RUNNING = "running"
const STEP_STATUS_SCHEDULED = "scheduled"
const STEP_STATUS_STOPPED = "stopped"
const STEP_STATUS_SUCCESS = "success"

const STEP_DEFINITION_STATUS_DRAFT = "draft"
const STEP_DEFINITION_STATUS_ACTIVE = "active"
const STEP_DEFINITION_STATUS_INACTIVE = "inactive"
